### ISSUE TITLE
Book names are shorten

### ISSUE THREAD

**Issue by alexbadm** [vrybant/unboundbible-mac#2]
Book names are shorten although the area is wide enough
<img width="419" alt="Снимок экрана 2021-08-12 в 09 58 46" src="https://user-images.githubusercontent.com/8415399/129152682-9e70ba36-3353-4bd3-bb98-4fdc312f53d5.png">

**Comment by vrybant** [comment]
Thank you for your feedback. I'll fix it.

**Comment by vrybant** [comment]
The bug is fixed in version 5.3
